# Mount Google Drive

In [ ]:
from google.colab import drive
drive.mount('/content/gdrive')

Mounted at /content/gdrive


# Install ONNXRuntime

In [ ]:
!tar -zxf "gdrive/MyDrive/Colab Notebooks/onnxruntime-linux-x64-1.14.1.tgz" -C "."

In [ ]:
!pip install colab-env --upgrade

import os
from colab_env import envvar_handler
envvar_handler.add_env('ONNXRUNTIME_DIR', '/content/onnxruntime-linux-x64-1.14.1')
ld_library_path = os.getenv('LD_LIBRARY_PATH')
envvar_handler.add_env('LD_LIBRARY_PATH', '/content/onnxruntime-linux-x64-1.14.1/lib:' + ld_library_path)

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/
  Preparing metadata (setup.py) ... done
  Created wheel for colab-env: filename=colab_env-0.2.0-py3-none-any.whl size=3807 sha256=efa0c58c37f5232cc178c14e83ef8c1f2bd3424e685c8a3ab185ea50d3c42430
  Stored in directory: /root/.cache/pip/wheels/ae/36/4f/466c2cd4db5d08f317893a920c4a0f58a81459ee3bdb136d35
Successfully built colab-env
Drive already mounted at /content/gdrive; to attempt to forcibly remount, call drive.mount("/content/gdrive", force_remount=True).


# --Install Cuda 11.3

In [ ]:
!wget https://developer.download.nvidia.com/compute/cuda/repos/ubuntu2004/x86_64/cuda-ubuntu2004.pin
!sudo mv cuda-ubuntu2004.pin /etc/apt/preferences.d/cuda-repository-pin-600
!sudo apt-key adv --fetch-keys https://developer.download.nvidia.com/compute/cuda/repos/ubuntu2004/x86_64/3bf863cc.pub
!sudo add-apt-repository "deb https://developer.download.nvidia.com/compute/cuda/repos/ubuntu2004/x86_64/ /"
!sudo apt-get update

 # installing CUDA-11.3
!sudo apt install cuda-11-3

--2023-04-29 13:04:21--  https://developer.download.nvidia.com/compute/cuda/repos/ubuntu2004/x86_64/cuda-ubuntu2004.pin
Resolving developer.download.nvidia.com (developer.download.nvidia.com)... 152.195.19.142
Connecting to developer.download.nvidia.com (developer.download.nvidia.com)|152.195.19.142|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 190 [application/octet-stream]
Saving to: ‘cuda-ubuntu2004.pin’

cuda-ubuntu2004.pin 100%[===================>]     190  --.-KB/s    in 0s      

2023-04-29 13:04:21 (9.34 MB/s) - ‘cuda-ubuntu2004.pin’ saved [190/190]

Executing: /tmp/apt-key-gpghome.jZbHuSbNUs/gpg.1.sh --fetch-keys https://developer.download.nvidia.com/compute/cuda/repos/ubuntu2004/x86_64/3bf863cc.pub
gpg: requesting key from 'https://developer.download.nvidia.com/compute/cuda/repos/ubuntu2004/x86_64/3bf863cc.pub'
gpg: key A4B469963BF863CC: "cudatools <cudatools@nvidia.com>" not changed
gpg: Total number processed: 1
gpg:              unchanged: 1
Ge

In [ ]:
# setup your paths
!echo 'export PATH=/usr/local/cuda-11.3/bin:$PATH' >> ~/.bashrc
!echo 'export LD_LIBRARY_PATH=/usr/local/cuda-11.3/lib64:$LD_LIBRARY_PATH' >> ~/.bashrc
!source ~/.bashrc
!sudo ldconfig



In [ ]:
# Finally, to verify the installation, check
!nvidia-smi
!nvcc -V

/bin/bash: nvidia-smi: command not found
nvcc: NVIDIA (R) Cuda compiler driver
Copyright (c) 2005-2022 NVIDIA Corporation
Built on Wed_Sep_21_10:33:58_PDT_2022
Cuda compilation tools, release 11.8, V11.8.89
Build cuda_11.8.r11.8/compiler.31833905_0


# --Install TensorRT 8.4


In [ ]:

!cp "drive/MyDrive/Colab Notebooks/TensorRT-8.6.0.12.Linux.x86_64-gnu.cuda-11.8.tar.gz" "."

!tar -xf TensorRT-8.6.0.12.Linux.x86_64-gnu.cuda-11.8.tar.gz

In [ ]:
#Add the absolute path to the TensorRTlib directory to the environment variable LD_LIBRARY_PATH:
version="8.6.0.12"
!export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:<TensorRT-${version}/lib>

/bin/bash: -c: line 0: syntax error near unexpected token `newline'
/bin/bash: -c: line 0: `export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:<TensorRT-${version}/lib>'


In [ ]:
#Install the Python TensorRT wheel file.
%cd TensorRT-{version}/python

!python3 -m pip install tensorrt-8.6.0-cp310-none-linux_x86_64.whl

/content/TensorRT-8.6.0.12/python
Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/
Processing ./tensorrt-8.6.0-cp310-none-linux_x86_64.whl


In [ ]:
#Install the Python graphsurgeon wheel file.
%cd ../graphsurgeon

!python3 -m pip install graphsurgeon-0.4.6-py2.py3-none-any.whl

/content/TensorRT-8.6.0.12
/content/TensorRT-8.6.0.12/graphsurgeon
Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/
Processing ./graphsurgeon-0.4.6-py2.py3-none-any.whl


In [ ]:
#Install the Python onnx-graphsurgeon wheel file.
%cd ../onnx_graphsurgeon

!python3 -m pip install onnx_graphsurgeon-0.3.12-py2.py3-none-any.whl

/content/TensorRT-8.6.0.12/onnx_graphsurgeon
Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/
Processing ./onnx_graphsurgeon-0.3.12-py2.py3-none-any.whl


In [ ]:
!dpkg -l | grep nvinfer

# Install MMPose

In [ ]:
#Step 1. Install MMEngine and MMCV using MIM.
!pip3 install openmim
!mim install mmengine
!mim install "mmcv>=2.0.0"

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 51.3/51.3 kB 5.5 MB/s eta 0:00:00
Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/
Looking in links: https://download.openmmlab.com/mmcv/dist/cu118/torch2.0.0/index.html
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 374.3/374.3 kB 7.4 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 250.3/250.3 kB 28.8 MB/s eta 0:00:00
  Attempting uninstall: platformdirs
    Found existing installation: platformdirs 3.3.0
    Uninstalling platformdirs-3.3.0:
      Successfully uninstalled platformdirs-3.3.0
Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/
Looking in links: https://download.openmmlab.com/mmcv/dist/cu118/torch2.0.0/index.html
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 74.4/74.4 MB 8.4 MB/s eta 0:00:00


In [ ]:
#Step 2. Install MMPose from the source.
!git clone https://github.com/open-mmlab/mmpose.git
%cd mmpose
!pip install -e .

Cloning into 'mmpose'...
remote: Enumerating objects: 27693, done.
remote: Counting objects: 100% (1517/1517), done.
remote: Compressing objects: 100% (792/792), done.
remote: Total 27693 (delta 846), reused 1231 (delta 698), pack-reused 26176
Receiving objects: 100% (27693/27693), 31.53 MiB | 25.30 MiB/s, done.
Resolving deltas: 100% (19526/19526), done.
/content/mmpose
Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/
Obtaining file:///content/mmpose
  Preparing metadata (setup.py) ... done
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 50.6/50.6 kB 2.7 MB/s eta 0:00:00
  Preparing metadata (setup.py) ... done
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 286.4/286.4 kB 26.0 MB/s eta 0:00:00
  Created wheel for chumpy: filename=chumpy-0.70-py3-none-any.whl size=58268 sha256=919961c6060431d48345cc58e1b2df4eeb818c5437cc4c77023209bcd28544aa
  Stored in directory: /root/.cache/pip/wheels/e0/c1/ef/29ba7be03653a29ef6f2c3e1956d6c4d8877f2b243af41

In [ ]:
#Step 3. Verification of mmpose
import mmpose
print(mmpose.__version__)
# Example output: 1.0.0

import mmcv
print(mmcv.__version__)

%cd ..

1.0.0
2.0.0
/content


# Install MMDeploy

In [ ]:
# Clone the repos
!git clone https://github.com/open-mmlab/mmdeploy.git
!git clone https://github.com/open-mmlab/mmsegmentation.git

!git clone https://github.com/open-mmlab/mmdetection.git
!pip install -e mmdetection/.

Cloning into 'mmdeploy'...
remote: Enumerating objects: 23821, done.
remote: Counting objects: 100% (5906/5906), done.
remote: Compressing objects: 100% (958/958), done.
remote: Total 23821 (delta 5132), reused 5034 (delta 4932), pack-reused 17915
Receiving objects: 100% (23821/23821), 12.14 MiB | 21.03 MiB/s, done.
Resolving deltas: 100% (15524/15524), done.
Cloning into 'mmsegmentation'...
remote: Enumerating objects: 15117, done.
remote: Counting objects: 100% (683/683), done.
remote: Compressing objects: 100% (425/425), done.
remote: Total 15117 (delta 277), reused 468 (delta 226), pack-reused 14434
Receiving objects: 100% (15117/15117), 20.27 MiB | 24.71 MiB/s, done.
Resolving deltas: 100% (10597/10597), done.
Cloning into 'mmdetection'...
remote: Enumerating objects: 36626, done.
remote: Counting objects: 100% (1280/1280), done.
remote: Compressing objects: 100% (707/707), done.
remote: Total 36626 (delta 720), reused 939 (delta 559), pack-reused 35346
Receiving objects: 100% (36

In [ ]:
# Install the libraries
#On GPU:
#!pip install torch==1.10.1+cu111 torchvision==0.11.2+cu111 torchaudio==0.10.1 -f https://download.pytorch.org/whl/torch_stable.html
#On Cpu
!pip install pytorch==1.8.0 torchvision==0.11.2+cu111 cpuonly -c pytorch -f https://download.pytorch.org/whl/torch_stable.html
#!pip install mmcv-full -f https://download.openmmlab.com/mmcv/dist/cu111/torch1.10/index.html
!pip install mmsegmentation==0.25
!pip install onnxruntime

ERROR: Could not open requirements file: [Errno 2] No such file or directory: 'pytorch'
Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 805.0/805.0 kB 10.5 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 648.8/648.8 kB 39.4 MB/s eta 0:00:00
Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 5.9/5.9 MB 35.8 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 46.0/46.0 kB 3.9 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 86.8/86.8 kB 9.8 MB/s eta 0:00:00


In [ ]:

!pip install -e mmdeploy/. build

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/
Obtaining file:///content/mmdeploy
  Preparing metadata (setup.py) ... done
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 131.8/131.8 kB 3.4 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 134.3/134.3 kB 15.0 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 14.6/14.6 MB 83.4 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.1/1.1 MB 35.4 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 110.5/110.5 kB 11.2 MB/s eta 0:00:00
  Attempting uninstall: protobuf
    Found existing installation: protobuf 3.20.3
    Uninstalling protobuf-3.20.3:
      Successfully uninstalled protobuf-3.20.3
  Running setup.py develop for mmdeploy
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
tensorflow 2.12.0 requires protobuf!=4.21.0,

In [ ]:

%cd mmdetection
!pip install -e . build
%cd ..

/content/mmdetection
Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/
Obtaining file:///content/mmdetection
  Preparing metadata (setup.py) ... done
  Attempting uninstall: mmdet
    Found existing installation: mmdet 3.0.0
    Uninstalling mmdet-3.0.0:
      Successfully uninstalled mmdet-3.0.0
  Running setup.py develop for mmdet
/content


In [ ]:
!mim install mmdet
import mmdet
print(mmdet.__version__)

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/
Looking in links: https://download.openmmlab.com/mmcv/dist/cu118/torch2.0.0/index.html
Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 343.5/343.5 kB 7.1 MB/s eta 0:00:00
  Preparing metadata (setup.py) ... done
Saved /tmp/tmp851d0pro/mmsegmentation-0.25.0.tar.gz
Successfully downloaded mmsegmentation
Get 'mim' extra requirements from `mminstall.txt` for mmsegmentation 0.25.0: ['mmcls>=0.20.1', 'mmcv-full<=1.6.0,>=1.4.4'].
3.0.0


In [ ]:
!python ./mmdeploy/tools/check_env.py

06/13 18:17:32 - mmengine - INFO - 

06/13 18:17:32 - mmengine - INFO - **********Environmental information**********
06/13 18:17:33 - mmengine - INFO - sys.platform: linux
06/13 18:17:33 - mmengine - INFO - Python: 3.10.12 (main, Jun  7 2023, 12:45:35) [GCC 9.4.0]
06/13 18:17:33 - mmengine - INFO - CUDA available: False
06/13 18:17:33 - mmengine - INFO - numpy_random_seed: 2147483648
06/13 18:17:33 - mmengine - INFO - GCC: x86_64-linux-gnu-gcc (Ubuntu 9.4.0-1ubuntu1~20.04.1) 9.4.0
06/13 18:17:33 - mmengine - INFO - PyTorch: 2.0.1+cu118
06/13 18:17:33 - mmengine - INFO - PyTorch compiling details: PyTorch built with:
  - GCC 9.3
  - C++ Version: 201703
  - Intel(R) oneAPI Math Kernel Library Version 2022.2-Product Build 20220804 for Intel(R) 64 architecture applications
  - Intel(R) MKL-DNN v2.7.3 (Git Hash 6dbeffbae1f23cbbeae17adb7b5b13f1f37c080e)
  - OpenMP 201511 (a.k.a. OpenMP 4.5)
  - LAPACK is enabled (usually provided by MKL)
  - NNPACK is enabled
  - CPU capability usage: AVX2


# Prepare datasets

In [ ]:
!mkdir mmpose/data

In [ ]:
# Prepare Halpe dataset
!tar -zxf "gdrive/MyDrive/Colab Notebooks/data/halpe.tgz" -C "mmpose/data"

In [ ]:
# Prepare COCO WholeBody dataset
!tar -zxf "gdrive/MyDrive/Colab Notebooks/data/coco_wholebody.tar.gz" -C "mmpose/data"

In [ ]:
!pip install xtcocotools

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/


# RTMPose

In [ ]:
# go to the mmdeploy folder
%cd mmdeploy

/content/mmdeploy


In [ ]:
!pip install numpy --upgrade

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 17.3/17.3 MB 51.7 MB/s eta 0:00:00
  Attempting uninstall: numpy
    Found existing installation: numpy 1.22.4
    Uninstalling numpy-1.22.4:
      Successfully uninstalled numpy-1.22.4
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
numba 0.56.4 requires numpy<1.24,>=1.18, but you have numpy 1.24.3 which is incompatible.
tensorflow 2.12.0 requires numpy<1.24,>=1.22, but you have numpy 1.24.3 which is incompatible.
tensorflow 2.12.0 requires protobuf!=4.21.0,!=4.21.1,!=4.21.2,!=4.21.3,!=4.21.4,!=4.21.5,<5.0.0dev,>=3.20.3, but you have protobuf 3.20.2 which is incompatible.


In [ ]:
# Copy model for wholebody pose estimation
!mkdir models
!cp "../gdrive/MyDrive/Colab Notebooks/rtmpose-l_simcc-coco-wholebody_pt-aic-coco_270e-384x288-eaeb96c8_20230125.pth" models

In [ ]:
!python tools/deploy.py \
    configs/mmpose/pose-detection_simcc_onnxruntime_dynamic.py \
    ../mmpose/projects/rtmpose/rtmpose/wholebody_2d_keypoint/rtmpose-l_8xb32-270e_coco-wholebody-384x288.py \
    models/rtmpose-l_simcc-coco-wholebody_pt-aic-coco_270e-384x288-eaeb96c8_20230125.pth \
    "../gdrive/MyDrive/Colab Notebooks/images/030123129.jpg" \
    --work-dir rtmpose-ort/rtmpose-l \
    --device cpu \
    --show \
    --dump-info  # dump sdk info

05/01 16:07:37 - mmengine - WARNING - Failed to search registry with scope "mmpose" in the "Codebases" registry tree. As a workaround, the current "Codebases" registry in "mmdeploy" is used to build instance. This may cause unexpected failure when running the built modules. Please check whether "mmpose" is a correct scope, or whether the registry is initialized.
05/01 16:07:37 - mmengine - WARNING - Failed to search registry with scope "mmpose" in the "mmpose_tasks" registry tree. As a workaround, the current "mmpose_tasks" registry in "mmdeploy" is used to build instance. This may cause unexpected failure when running the built modules. Please check whether "mmpose" is a correct scope, or whether the registry is initialized.
05/01 16:07:41 - mmengine - INFO - Start pipeline mmdeploy.apis.pytorch2onnx.torch2onnx in subprocess
05/01 16:07:44 - mmengine - WARNING - Failed to search registry with scope "mmpose" in the "Codebases" registry tree. As a workaround, the current "Codebases" reg

In [ ]:
%cd ../mmpose
!mkdir output

/content/mmpose


In [ ]:
import os
import subprocess

def process_videos(directory, directory_output, det_config, det_checkpoint, pose_config, pose_checkpoint):
  for filename in os.listdir(directory):
    f = os.path.join(directory, filename)
    # checking if it is a file
    if os.path.isfile(f):
        print("Processing file: " + f)
        filepath, file_extension = os.path.splitext(f)
        filename = filepath.split("/")[-1]
        full_directory_output = directory_output + '/' + filename

        # Check if directory is available
        isExist = os.path.exists(full_directory_output)
        if not isExist:
          os.makedirs(full_directory_output)
          print("Created directory: " + full_directory_output)

        #cmd = 'python scripts/demo_inference.py --cfg {} --checkpoint {} --video {} --outdir "{}" --format open --save_video'
        cmd = 'python demo/topdown_demo_with_mmdet.py {} {} {} {} --input "{}" --device cpu --save-predictions --output-root {}'
        cmd = cmd.format(det_config, det_checkpoint, pose_config, pose_checkpoint, f, full_directory_output)
        print(cmd)

        p = subprocess.Popen(cmd, stdout=subprocess.PIPE, shell=True)
        out, err = p.communicate()



In [ ]:
!mkdir videos
!cp -r "../gdrive/MyDrive/Colab Notebooks/videos/." videos

In [ ]:
det_config = "projects/rtmpose/rtmdet/person/rtmdet_nano_320-8xb32_coco-person.py"
det_checkpoint = "https://download.openmmlab.com/mmpose/v1/projects/rtmpose/rtmdet_nano_8xb32-100e_coco-obj365-person-05d8511e.pth"
pose_config = "projects/rtmpose/rtmpose/wholebody_2d_keypoint/rtmpose-l_8xb32-270e_coco-wholebody-384x288.py"
pose_checkpoint = "../mmdeploy/models/rtmpose-l_simcc-coco-wholebody_pt-aic-coco_270e-384x288-eaeb96c8_20230125.pth"
process_videos("videos", "output", det_config, det_checkpoint, pose_config, pose_checkpoint)


Processing file: videos/clip_tri_1.mp4
Created directory: output/clip_tri_1
python demo/topdown_demo_with_mmdet.py projects/rtmpose/rtmdet/person/rtmdet_nano_320-8xb32_coco-person.py https://download.openmmlab.com/mmpose/v1/projects/rtmpose/rtmdet_nano_8xb32-100e_coco-obj365-person-05d8511e.pth projects/rtmpose/rtmpose/wholebody_2d_keypoint/rtmpose-l_8xb32-270e_coco-wholebody-384x288.py ../mmdeploy/models/rtmpose-l_simcc-coco-wholebody_pt-aic-coco_270e-384x288-eaeb96c8_20230125.pth --input "videos/clip_tri_1.mp4" --device cpu --save-predictions --output-root output/clip_tri_1
Processing file: videos/short.mp4
Created directory: output/short
python demo/topdown_demo_with_mmdet.py projects/rtmpose/rtmdet/person/rtmdet_nano_320-8xb32_coco-person.py https://download.openmmlab.com/mmpose/v1/projects/rtmpose/rtmdet_nano_8xb32-100e_coco-obj365-person-05d8511e.pth projects/rtmpose/rtmpose/wholebody_2d_keypoint/rtmpose-l_8xb32-270e_coco-wholebody-384x288.py ../mmdeploy/models/rtmpose-l_simcc-co

In [ ]:
!cp -r output "../gdrive/MyDrive/Colab Notebooks/RTMPose/predictions"

# Inference with SDK Python API

In [ ]:
%cd mmdeploy

/content/mmdeploy


In [ ]:
# for onnxruntime
!pip install mmdeploy-runtime

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 22.1/22.1 MB 50.5 MB/s eta 0:00:00


In [ ]:
!sudo mkdir -p example/python
!wget https://download.openmmlab.com/mmpose/v1/projects/rtmpose/rtmpose-cpu.zip
!unzip rtmpose-cpu.zip -d example/python

--2023-05-01 10:31:38--  https://download.openmmlab.com/mmpose/v1/projects/rtmpose/rtmpose-cpu.zip
Resolving download.openmmlab.com (download.openmmlab.com)... 8.25.82.207, 8.25.82.208, 8.25.82.211, ...
Connecting to download.openmmlab.com (download.openmmlab.com)|8.25.82.207|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 54564140 (52M) [application/zip]
Saving to: ‘rtmpose-cpu.zip’

rtmpose-cpu.zip     100%[===================>]  52.04M  14.9MB/s    in 3.7s    

2023-05-01 10:31:42 (14.2 MB/s) - ‘rtmpose-cpu.zip’ saved [54564140/54564140]

Archive:  rtmpose-cpu.zip
   creating: example/python/rtmpose-ort/
  inflating: example/python/rtmpose-ort/000000147979.jpg  
   creating: example/python/rtmpose-ort/rtmdet-nano/
  inflating: example/python/rtmpose-ort/rtmdet-nano/deploy.json  
  inflating: example/python/rtmpose-ort/rtmdet-nano/detail.json  
  inflating: example/python/rtmpose-ort/rtmdet-nano/end2end.onnx  
  inflating: example/python/rtmpose-ort/rtmdet-n

In [ ]:
# go to ./example/python
#!cd example/python

# Please pass the folder of the model, not the model file
# Format:
# python pose_tracker.py cpu {det work-dir} {pose work-dir} {your_video.mp4}

# Example:
#!python demo/python/pose_tracker.py cpu example/python/rtmpose-ort/rtmdet-nano/ example/python/rtmpose-ort/rtmpose-m/ "tests/data/arm_wrestling.mp4" --output example/python
!python demo/python/pose_tracker.py cpu example/python/rtmpose-ort/rtmdet-nano/ example/python/rtmpose-ort/rtmpose-m/ "../gdrive/MyDrive/Colab Notebooks/videos/clip_tri_3.mp4" --output example

python3: can't open file '/content/mmpose/demo/python/pose_tracker.py': [Errno 2] No such file or directory


In [ ]:
# Copyright (c) OpenMMLab. All rights reserved.
import argparse

import cv2
import numpy as np
from mmdeploy_runtime import PoseDetector


def parse_args():
    parser = argparse.ArgumentParser(
        description='show how to use sdk python api')
    parser.add_argument('device_name', help='name of device, cuda or cpu')
    parser.add_argument(
        'model_path',
        help='path of mmdeploy SDK model dumped by model converter')
    parser.add_argument('image_path', help='path of an image')
    parser.add_argument(
        '--bbox',
        default=None,
        nargs='+',
        type=int,
        help='bounding box of an object in format (x, y, w, h)')
    args = parser.parse_args()
    return args


def main():
    args = parse_args()

    img = cv2.imread(args.image_path)

    detector = PoseDetector(
        model_path=args.model_path, device_name=args.device_name, device_id=0)

    if args.bbox is None:
        result = detector(img)
    else:
        # converter (x, y, w, h) -> (left, top, right, bottom)
        print(args.bbox)
        bbox = np.array(args.bbox, dtype=int)
        bbox[2:] += bbox[:2]
        result = detector(img, bbox)
    print(result)

    _, point_num, _ = result.shape
    points = result[:, :, :2].reshape(point_num, 2)
    for [x, y] in points.astype(int):
        cv2.circle(img, (x, y), 1, (0, 255, 0), 2)

    cv2.imwrite('output_pose.png', img)


if __name__ == '__main__':
    main()

In [ ]:
import cv2
import numpy as np
from mmdeploy_runtime import PoseDetector

img = cv2.imread('example/000000.jpg')
img = cv2.imread('../gdrive/MyDrive/Colab Notebooks/images/073675635.jpg')

# create a detector
detector = PoseDetector(model_path='example/python/rtmpose-ort/rtmpose-m', device_name='cpu', device_id=0)

result = detector(img)
print(result)

_, point_num, _ = result.shape
points = result[:, :, :2].reshape(point_num, 2)
for [x, y] in points.astype(int):
    cv2.circle(img, (x, y), 1, (0, 255, 0), 2)

cv2.imwrite('output_pose.png', img)

def other():
  # run the inference
  bboxes, labels, _ = detector(img)
  # Filter the result according to threshold
  indices = [i for i in range(len(bboxes))]
  for index, bbox, label_id in zip(indices, bboxes, labels):
    [left, top, right, bottom], score = bbox[0:4].astype(int),  bbox[4]
    if score < 0.3:
        continue
    cv2.rectangle(img, (left, top), (right, bottom), (0, 255, 0))

  cv2.imwrite('output_073675635.png', img)

[[[4.4036365e+02 9.9965149e+01 5.4263908e-01]
  [4.4590918e+02 9.4383728e+01 5.5045694e-01]
  [4.4036365e+02 9.4383728e+01 5.1719379e-01]
  [4.7086365e+02 9.1593079e+01 6.1002660e-01]
  [4.4868188e+02 9.4383728e+01 5.4520655e-01]
  [4.9859094e+02 1.3903485e+02 4.8968795e-01]
  [4.6531824e+02 1.3345349e+02 4.3710089e-01]
  [5.1245459e+02 2.1159302e+02 3.6532703e-01]
  [4.8750000e+02 2.2275586e+02 2.6921096e-01]
  [4.7918176e+02 2.4787207e+02 2.1964073e-01]
  [4.9859094e+02 2.5903491e+02 1.6019998e-01]
  [4.9581824e+02 2.5624420e+02 5.4851049e-01]
  [4.8750000e+02 2.5624420e+02 5.1383531e-01]
  [4.7363635e+02 3.3717438e+02 4.3691197e-01]
  [4.7363635e+02 3.3438373e+02 4.3040937e-01]
  [5.1522729e+02 3.9019769e+02 3.3143798e-01]
  [5.2077271e+02 3.6508136e+02 3.3976722e-01]]]
